"""Initial schema: thirty-one tables, and the constraints that carry the invariants.

Generated from ``revora.persistence.models`` and then annotated, because several of
the objects below are not ordinary schema — they are the mechanism behind a claim the
design makes, and a future reader deleting one for being "redundant" would remove the
guarantee with it. Each of those carries a comment naming what it protects, and the
four load-bearing ones also get a ``COMMENT ON`` in the database itself, so the
reason survives being read through ``psql`` rather than through this file.

The four:

* ``uq_webhook_event_merchant_id_provider_event_id`` — duplicate webhook delivery is
  safe. The provider retries and two retries can arrive at once; the insert is
  ``ON CONFLICT DO NOTHING`` and zero rows means duplicate.
* ``one_open_case_per_payment`` — one open case per payment. Partial over the
  non-terminal states, so a payment that fails again later still gets a new case.
* ``uq_execution_intent_merchant_id_idempotency_key`` — one external effect per
  authorization. The intent is written before the provider call, so a retry collides
  and reconciles instead of calling twice.
* ``uq_audit_record_case_id_seq`` — gap-free per-case audit ordering, together with
  the allocation from ``recovery_case.audit_seq``.

Ordering note: ``policy_decision.consumed_by_intent_id`` deliberately has no foreign
key to ``execution_intent``, which already references ``policy_decision``. A key in
both directions is a cycle every creation order has to work around, and the
uniqueness — not the key — is what carries the invariant.

Revision ID: 0001
Revises:
Create Date: 2026-08-30 20:09:34.443626+00:00
"""

# ruff: noqa: E501
# Line length is not enforced in migration bodies. Reflowing an autogenerated
# `op.create_table` makes it harder to diff against the next autogeneration, and a
# migration is read for what it does to the schema rather than as prose.

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_INVARIANT_COMMENTS: tuple[str, ...] = (
    "COMMENT ON CONSTRAINT uq_webhook_event_merchant_id_provider_event_id "
    "ON webhook_event IS "
    "'Guarantees duplicate webhook delivery is safe: concurrent redeliveries of one "
    "provider_event_id yield exactly one persisted event (R1.C4, property P4).'",
    "COMMENT ON INDEX one_open_case_per_payment IS "
    "'Guarantees one open recovery case per payment. Partial over the non-terminal "
    "states, so a payment that fails again later still gets a new case.'",
    "COMMENT ON CONSTRAINT uq_execution_intent_merchant_id_idempotency_key "
    "ON execution_intent IS "
    "'Guarantees exactly one external effect per authorization: the intent is written "
    "before the provider call, so a retry collides here and reconciles (property P3).'",
    "COMMENT ON CONSTRAINT uq_audit_record_case_id_seq ON audit_record IS "
    "'Guarantees gap-free per-case audit ordering, together with sequence allocation "
    "from recovery_case.audit_seq in the same transaction (property P12).'",
    "COMMENT ON CONSTRAINT ck_recovery_case_counters_within_bounds ON recovery_case IS "
    "'Schema-level backstop above the configured bounds. customer_message_count can "
    "never exceed executed_action_count, so a policy bug cannot double a message.'",
)


def upgrade() -> None:
    # ``gen_random_uuid()`` is built into Postgres 13 and later. The extension is
    # created anyway so this migration also applies to an older server rather than
    # failing on the first table's default.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table('merchant',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('default_currency', sa.CHAR(length=3), server_default='INR', nullable=False),
    sa.Column('state', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('reporting_timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant')),
    sa.UniqueConstraint('slug', name='uq_merchant_slug')
    )
    op.create_table('customer_consent',
    sa.Column('customer_key', sa.Text(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('effective_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consent_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_customer_consent_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_consent'))
    )
    # Reason: the opt-out check in the policy hot path. Every decision that could
    # produce a customer-visible action performs this lookup.
    op.create_index('ix_customer_consent_merchant_id_customer_key', 'customer_consent', ['merchant_id', 'customer_key'], unique=False)
    op.create_table('event_quarantine',
    sa.Column('provider_event_id', sa.Text(), nullable=True),
    sa.Column('validation_rule', sa.Text(), nullable=False),
    sa.Column('raw_payload_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('raw_payload_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.SmallInteger(), nullable=True),
    sa.Column('payload_bytes', sa.Integer(), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('retain_until', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_event_quarantine_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_quarantine'))
    )
    op.create_index('ix_event_quarantine_merchant_id_retain_until', 'event_quarantine', ['merchant_id', 'retain_until'], unique=False)
    op.create_table('experiment',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='DRAFT', nullable=False),
    sa.Column('primary_metric', sa.Text(), nullable=False),
    sa.Column('secondary_metrics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allocation_ratio', sa.Text(), server_default='1:1', nullable=False),
    sa.Column('assumed_baseline_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('minimum_detectable_effect', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('significance_level', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('power', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('analysis_method', sa.Text(), nullable=True),
    sa.Column('required_sample_size_per_group', sa.Integer(), nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"state" IN (\'DRAFT\', \'ACTIVE\', \'COMPLETED\', \'ABANDONED\')', name=op.f('ck_experiment_state_enum')),
    sa.CheckConstraint('power > 0 AND power < 1', name=op.f('ck_experiment_power_in_range')),
    sa.CheckConstraint('required_sample_size_per_group > 0', name=op.f('ck_experiment_required_sample_size_positive')),
    sa.CheckConstraint('significance_level > 0 AND significance_level < 1', name=op.f('ck_experiment_significance_level_in_range')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_experiment_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment')),
    sa.UniqueConstraint('merchant_id', 'name', name='uq_experiment_merchant_id_name')
    )
    op.create_index('ix_experiment_merchant_id_state', 'experiment', ['merchant_id', 'state'], unique=False)
    op.create_table('merchant_user',
    sa.Column('email_masked', sa.Text(), nullable=False),
    sa.Column('email_key', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_merchant_user_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_user')),
    sa.UniqueConstraint('merchant_id', 'email_key', name='uq_merchant_user_merchant_id_email_key')
    )
    op.create_table('model_version',
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='INACTIVE', nullable=False),
    sa.Column('training_observation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('synthetic_observation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_snapshot_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("state IN ('INACTIVE', 'ACTIVE', 'RETIRED')", name=op.f('ck_model_version_state_known')),
    sa.CheckConstraint('training_observation_count >= 0 AND synthetic_observation_count >= 0', name=op.f('ck_model_version_observation_counts_nonnegative')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_model_version_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_version')),
    sa.UniqueConstraint('merchant_id', 'component', 'version_label', name='uq_model_version_merchant_component_label')
    )
    op.create_index('one_active_model_version_per_component', 'model_version', ['merchant_id', 'component'], unique=True, postgresql_where=sa.text("state = 'ACTIVE'"))
    op.create_table('synthetic_run',
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ground_truth', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generator_version', sa.Text(), nullable=True),
    sa.Column('case_count', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_synthetic_run_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synthetic_run')),
    sa.UniqueConstraint('merchant_id', 'seed', 'scenario', name='uq_synthetic_run_merchant_seed_scenario')
    )
    # INVARIANT: duplicate webhook delivery is safe.
    # uq_webhook_event_merchant_id_provider_event_id below is the single object that
    # makes it so. Concurrent redeliveries of one provider_event_id yield exactly one
    # persisted row, which is why no second recovery case can open for the same
    # failure and no customer gets contacted twice for it.
    op.create_table('webhook_event',
    sa.Column('provider_event_id', sa.Text(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('raw_payload_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('raw_payload_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.SmallInteger(), nullable=True),
    sa.Column('canonical', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('processing_state', sa.Text(), server_default='RECEIVED', nullable=False),
    sa.Column('retain_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_webhook_event_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_event')),
    sa.UniqueConstraint('merchant_id', 'provider_event_id', name='uq_webhook_event_merchant_id_provider_event_id')
    )
    op.create_index('ix_webhook_event_correlation_id', 'webhook_event', ['correlation_id'], unique=False)
    op.create_index('ix_webhook_event_merchant_id_received_at', 'webhook_event', ['merchant_id', 'received_at'], unique=False)
    op.create_table('app_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_kind', sa.Text(), nullable=False),
    sa.Column('config_version', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('effective_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_assumption', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("value_kind IN ('INTEGER', 'DURATION_SECONDS', 'DECIMAL', 'MONEY_MINOR', 'STRING', 'STRING_SET')", name=op.f('ck_app_config_value_kind_known')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['merchant_user.id'], name=op.f('fk_app_config_approved_by_user_id_merchant_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_app_config_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_config')),
    sa.UniqueConstraint('merchant_id', 'key', 'config_version', name='uq_app_config_merchant_key_version')
    )
    op.create_index('ix_app_config_merchant_id_key', 'app_config', ['merchant_id', 'key'], unique=False)
    op.create_index('one_active_config_per_key', 'app_config', ['merchant_id', 'key'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('experiment_version_freeze',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('fk_experiment_version_freeze_experiment_id_experiment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_experiment_version_freeze_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_version_freeze')),
    sa.UniqueConstraint('experiment_id', 'component', name='uq_experiment_version_freeze_experiment_id_component')
    )
    op.create_table('model_promotion',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('prior_version_id', sa.UUID(), nullable=True),
    sa.Column('approving_user_id', sa.UUID(), nullable=False),
    sa.Column('promoted_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('evaluation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('prior_version_id IS NULL OR prior_version_id <> model_version_id', name=op.f('ck_model_promotion_promotion_changes_version')),
    sa.ForeignKeyConstraint(['approving_user_id'], ['merchant_user.id'], name=op.f('fk_model_promotion_approving_user_id_merchant_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_model_promotion_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], name=op.f('fk_model_promotion_model_version_id_model_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prior_version_id'], ['model_version.id'], name=op.f('fk_model_promotion_prior_version_id_model_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_promotion'))
    )
    op.create_index('ix_model_promotion_model_version_id', 'model_promotion', ['model_version_id'], unique=False)
    op.create_table('policy_rule_set',
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retired_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approving_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approving_user_id'], ['merchant_user.id'], name=op.f('fk_policy_rule_set_approving_user_id_merchant_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_policy_rule_set_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rule_set')),
    sa.UniqueConstraint('merchant_id', 'version_label', name='uq_policy_rule_set_merchant_id_version_label')
    )
    op.create_index('one_active_rule_set_per_merchant', 'policy_rule_set', ['merchant_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('recovery_case',
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('provider_payment_id', sa.Text(), nullable=False),
    sa.Column('provider_order_id', sa.Text(), nullable=True),
    sa.Column('payment_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('customer_key', sa.Text(), nullable=False),
    sa.Column('customer_contact_masked', sa.Text(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_end_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('executed_action_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('customer_message_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('decision_cycle_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_outbound_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('audit_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('human_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('human_assigned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('verified_payment_status', sa.Text(), nullable=True),
    sa.Column('verified_amount_refunded', sa.BigInteger(), nullable=True),
    sa.Column('risk_flagged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('terminal_reason', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), server_default='REAL', nullable=False),
    sa.Column('synthetic_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"provenance" IN (\'REAL\', \'SYNTHETIC\')', name=op.f('ck_recovery_case_provenance_enum')),
    sa.CheckConstraint('"state" IN (\'NEW\', \'DETECTED\', \'DIAGNOSED\', \'DECISION_PENDING\', \'POLICY_CHECK\', \'ACTION_SCHEDULED\', \'EXECUTING\', \'WAITING_FOR_OUTCOME\', \'RECOVERED\', \'STOPPED\', \'BLOCKED\', \'EXPIRED\', \'ESCALATED\', \'FAILED\')', name=op.f('ck_recovery_case_state_enum')),
    sa.CheckConstraint('"terminal_reason" IN (\'RECOVERED_VERIFIED\', \'RECOVERY_WINDOW_ELAPSED\', \'MAX_ATTEMPTS_REACHED\', \'DECISION_CYCLE_LIMIT_REACHED\', \'CUSTOMER_OPTED_OUT\', \'ALREADY_PAID\', \'FRAUD_OR_RISK_FLAG\', \'PAYMENT_STATE_UNVERIFIABLE\', \'EXECUTION_RESULT_UNVERIFIABLE\', \'POLICY_BLOCKED\', \'HUMAN_OWNERSHIP\', \'COMMUNICATION_FAILED\')', name=op.f('ck_recovery_case_terminal_reason_enum')),
    sa.CheckConstraint('executed_action_count <= 10 AND customer_message_count <= executed_action_count AND decision_cycle_count <= 10 AND audit_seq <= 10000', name=op.f('ck_recovery_case_counters_within_bounds')),
    sa.CheckConstraint('executed_action_count >= 0 AND customer_message_count >= 0 AND decision_cycle_count >= 0 AND audit_seq >= 0', name=op.f('ck_recovery_case_counters_nonnegative')),
    sa.CheckConstraint('payment_amount > 0', name=op.f('ck_recovery_case_payment_amount_positive')),
    sa.ForeignKeyConstraint(['human_owner_user_id'], ['merchant_user.id'], name=op.f('fk_recovery_case_human_owner_user_id_merchant_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_recovery_case_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_event_id'], ['webhook_event.id'], name=op.f('fk_recovery_case_source_event_id_webhook_event'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['synthetic_run_id'], ['synthetic_run.id'], name=op.f('fk_recovery_case_synthetic_run_id_synthetic_run'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_case'))
    )
    op.create_index('ix_recovery_case_merchant_id_customer_key', 'recovery_case', ['merchant_id', 'customer_key'], unique=False)
    # Reason: cohort aggregation and dashboard ordering — "this merchant's cases,
    # newest first" is every list query the merchant ever sees.
    op.create_index('ix_recovery_case_merchant_id_detected_at', 'recovery_case', ['merchant_id', 'detected_at'], unique=False)
    # Reason: the lifecycle sweeper scan. Runs every LIFECYCLE_EVALUATION_INTERVAL
    # over non-terminal cases whose window is closing; the hottest periodic query.
    op.create_index('ix_recovery_case_merchant_id_state_window_end_at', 'recovery_case', ['merchant_id', 'state', 'window_end_at'], unique=False)
    # INVARIANT: one open case per payment.
    # Partial over the non-terminal states, generated from
    # domain.transitions.TERMINAL_STATES. A terminal case stops being covered, which
    # is deliberate: a payment that fails again later deserves a new case, and every
    # per-case bound then starts from zero for a genuinely new failure.
    op.create_index('one_open_case_per_payment', 'recovery_case', ['merchant_id', 'provider_payment_id'], unique=True, postgresql_where=sa.text("state NOT IN ('BLOCKED', 'ESCALATED', 'EXPIRED', 'FAILED', 'RECOVERED', 'STOPPED')"))
    op.create_table('webhook_secret',
    sa.Column('secret_ref', sa.Text(), nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('retired_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rotated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_webhook_secret_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rotated_by_user_id'], ['merchant_user.id'], name=op.f('fk_webhook_secret_rotated_by_user_id_merchant_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_secret')),
    sa.UniqueConstraint('merchant_id', 'secret_ref', name='uq_webhook_secret_merchant_id_secret_ref')
    )
    op.create_index('ix_webhook_secret_merchant_id_activated_at', 'webhook_secret', ['merchant_id', 'activated_at'], unique=False)
    op.create_table('ai_invocation',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('prompt_contract_id', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('influenced_recommendation', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_response_truncated', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_ai_invocation_latency_nonnegative')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_ai_invocation_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_ai_invocation_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_invocation'))
    )
    op.create_index('ix_ai_invocation_case_id', 'ai_invocation', ['case_id'], unique=False)
    op.create_index('ix_ai_invocation_merchant_id_created_at', 'ai_invocation', ['merchant_id', 'created_at'], unique=False)
    # INVARIANT: gap-free per-case audit ordering.
    # uq_audit_record_case_id_seq is half of it; the other half is the allocation
    # from recovery_case.audit_seq inside the same transaction as the insert. A
    # Postgres sequence would leave gaps and max(seq)+1 would race.
    # Append-only enforcement — the revoked grant and the trigger — arrives in 0002.
    op.create_table('audit_record',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('new_state', sa.Text(), nullable=True),
    sa.Column('diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('policy_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('action_result', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('truncated_fields', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_audit_record_action_enum')),
    sa.CheckConstraint('"new_state" IN (\'NEW\', \'DETECTED\', \'DIAGNOSED\', \'DECISION_PENDING\', \'POLICY_CHECK\', \'ACTION_SCHEDULED\', \'EXECUTING\', \'WAITING_FOR_OUTCOME\', \'RECOVERED\', \'STOPPED\', \'BLOCKED\', \'EXPIRED\', \'ESCALATED\', \'FAILED\')', name=op.f('ck_audit_record_new_state_enum')),
    sa.CheckConstraint('"previous_state" IN (\'NEW\', \'DETECTED\', \'DIAGNOSED\', \'DECISION_PENDING\', \'POLICY_CHECK\', \'ACTION_SCHEDULED\', \'EXECUTING\', \'WAITING_FOR_OUTCOME\', \'RECOVERED\', \'STOPPED\', \'BLOCKED\', \'EXPIRED\', \'ESCALATED\', \'FAILED\')', name=op.f('ck_audit_record_previous_state_enum')),
    sa.CheckConstraint('(case_id IS NULL) = (seq IS NULL)', name=op.f('ck_audit_record_case_and_seq_together')),
    sa.CheckConstraint('seq IS NULL OR seq >= 1', name=op.f('ck_audit_record_seq_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_audit_record_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_audit_record_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_record')),
    sa.UniqueConstraint('case_id', 'seq', name='uq_audit_record_case_id_seq')
    )
    # Reason: trace one inbound event end to end, across every component and every
    # asynchronous job it spawned. The audit log is this system's observability.
    op.create_index('ix_audit_record_correlation_id', 'audit_record', ['correlation_id'], unique=False)
    op.create_index('ix_audit_record_merchant_id_occurred_at', 'audit_record', ['merchant_id', 'occurred_at'], unique=False)
    op.create_table('baseline_estimate',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('decision_cycle', sa.SmallInteger(), nullable=False),
    sa.Column('probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ci_low', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ci_high', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('uncertainty_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('segment_id', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), server_default='REAL', nullable=False),
    sa.Column('validation_status', sa.Text(), nullable=False),
    sa.Column('training_snapshot_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"method" IN (\'DETERMINISTIC\', \'PRIOR_FALLBACK\', \'UNCALIBRATED\', \'DEFINITIONAL\')', name=op.f('ck_baseline_estimate_method_enum')),
    sa.CheckConstraint('"provenance" IN (\'REAL\', \'SYNTHETIC\')', name=op.f('ck_baseline_estimate_provenance_enum')),
    sa.CheckConstraint('"validation_status" IN (\'VALIDATED\', \'UNVALIDATED_BASELINE\', \'CALIBRATION_SUSPECT\', \'CALIBRATION_UNVERIFIED\')', name=op.f('ck_baseline_estimate_validation_status_enum')),
    sa.CheckConstraint('(uncertainty_available AND ci_low IS NOT NULL AND ci_high IS NOT NULL) OR (NOT uncertainty_available AND ci_low IS NULL AND ci_high IS NULL)', name=op.f('ck_baseline_estimate_interval_present_iff_available')),
    sa.CheckConstraint('ci_low IS NULL OR ci_high IS NULL OR ci_low <= ci_high', name=op.f('ck_baseline_estimate_interval_ordered')),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name=op.f('ck_baseline_estimate_probability_in_range')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_baseline_estimate_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_baseline_estimate_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], name=op.f('fk_baseline_estimate_model_version_id_model_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseline_estimate'))
    )
    op.create_index('ix_baseline_estimate_case_id_decision_cycle', 'baseline_estimate', ['case_id', 'decision_cycle'], unique=False)
    op.create_index('ix_baseline_estimate_merchant_id_segment_id', 'baseline_estimate', ['merchant_id', 'segment_id'], unique=False)
    op.create_table('detection_verdict',
    sa.Column('webhook_event_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"verdict" IN (\'AT_RISK\', \'NOT_AT_RISK\', \'DEFERRED_TRIGGER\')', name=op.f('ck_detection_verdict_verdict_enum')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_detection_verdict_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_detection_verdict_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_event.id'], name=op.f('fk_detection_verdict_webhook_event_id_webhook_event'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_verdict')),
    sa.UniqueConstraint('webhook_event_id', name='uq_detection_verdict_webhook_event_id')
    )
    op.create_index('ix_detection_verdict_merchant_id_decided_at', 'detection_verdict', ['merchant_id', 'decided_at'], unique=False)
    op.create_table('experiment_assignment',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('group', sa.Text(), nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('contaminated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"group" IN (\'CONTROL\', \'TREATMENT\')', name=op.f('ck_experiment_assignment_group_enum')),
    sa.CheckConstraint('excluded = (exclusion_reason IS NOT NULL)', name=op.f('ck_experiment_assignment_exclusion_reason_iff_excluded')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_experiment_assignment_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('fk_experiment_assignment_experiment_id_experiment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_experiment_assignment_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_assignment')),
    sa.UniqueConstraint('case_id', name='uq_experiment_assignment_case_id')
    )
    op.create_index('ix_experiment_assignment_experiment_id_group', 'experiment_assignment', ['experiment_id', 'group'], unique=False)
    op.create_table('job',
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('run_after', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("state IN ('PENDING', 'RUNNING', 'DONE', 'FAILED', 'DEAD_LETTER')", name=op.f('ck_job_state_known')),
    sa.CheckConstraint('attempts >= 0 AND max_attempts >= 1', name=op.f('ck_job_attempt_counts_sane')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_job_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_job_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index('ix_job_merchant_id_kind', 'job', ['merchant_id', 'kind'], unique=False)
    # Reason: the queue claim. Runs on every worker poll:
    # WHERE state='PENDING' AND run_after <= now() ORDER BY run_after
    # FOR UPDATE SKIP LOCKED.
    op.create_index('ix_job_state_run_after', 'job', ['state', 'run_after'], unique=False)
    # Guarantees: a periodic sweep cannot be enqueued twice. Partial on PENDING, so
    # the same dedupe key becomes enqueueable again once the job is claimed —
    # without that, the sweep would run exactly once and then never again.
    op.create_index('one_pending_job_per_dedupe_key', 'job', ['dedupe_key'], unique=True, postgresql_where=sa.text("state = 'PENDING' AND dedupe_key IS NOT NULL"))
    op.create_table('memory_observation',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('selected_action', sa.Text(), nullable=True),
    sa.Column('policy_verdict', sa.Text(), nullable=True),
    sa.Column('outcome_class', sa.Text(), nullable=True),
    sa.Column('realized_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('group', sa.Text(), nullable=True),
    sa.Column('executed_action_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('customer_message_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('decision_source', sa.Text(), nullable=True),
    sa.Column('intervention_status', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), server_default='REAL', nullable=False),
    sa.Column('trained_into_model_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"cause" IN (\'INSUFFICIENT_FUNDS\', \'EXPIRED_PAYMENT_METHOD\', \'BANK_OR_NETWORK_FAILURE\', \'TECHNICAL_ISSUE\', \'ABANDONMENT\', \'CUSTOMER_ACTION_REQUIRED\', \'FRAUD_OR_RISK_SIGNAL\', \'UNKNOWN\')', name=op.f('ck_memory_observation_cause_enum')),
    sa.CheckConstraint('"decision_source" IN (\'AUTOMATED\', \'HUMAN_OVERRIDE\', \'BASELINE_WORKFLOW\')', name=op.f('ck_memory_observation_decision_source_enum')),
    sa.CheckConstraint('"group" IN (\'CONTROL\', \'TREATMENT\')', name=op.f('ck_memory_observation_group_enum')),
    sa.CheckConstraint('"intervention_status" IN (\'NO_INTERVENTION_CONFIRMED\', \'REVORA_INTERVENED\', \'MERCHANT_INTERVENTION_UNKNOWN\')', name=op.f('ck_memory_observation_intervention_status_enum')),
    sa.CheckConstraint('"outcome_class" IN (\'NATURAL\', \'OBSERVED\', \'ATTRIBUTED\', \'NOT_ESTABLISHED\')', name=op.f('ck_memory_observation_outcome_class_enum')),
    sa.CheckConstraint('"policy_verdict" IN (\'APPROVED\', \'BLOCKED\', \'DEFERRED\', \'ESCALATE\')', name=op.f('ck_memory_observation_policy_verdict_enum')),
    sa.CheckConstraint('"provenance" IN (\'REAL\', \'SYNTHETIC\')', name=op.f('ck_memory_observation_provenance_enum')),
    sa.CheckConstraint('"selected_action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_memory_observation_selected_action_enum')),
    sa.CheckConstraint('realized_cost >= 0', name=op.f('ck_memory_observation_realized_cost_nonnegative')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_memory_observation_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_memory_observation_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trained_into_model_version_id'], ['model_version.id'], name=op.f('fk_memory_observation_trained_into_model_version_id_model_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_observation')),
    sa.UniqueConstraint('case_id', name='uq_memory_observation_case_id')
    )
    op.create_index('ix_memory_observation_merchant_id_intervention_status', 'memory_observation', ['merchant_id', 'intervention_status'], unique=False)
    op.create_table('payment_state_read',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('provider_payment_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('amount_refunded', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('captured', sa.Boolean(), nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount >= 0 AND amount_refunded >= 0', name=op.f('ck_payment_state_read_amounts_nonnegative')),
    sa.CheckConstraint('attempt_no >= 1', name=op.f('ck_payment_state_read_attempt_no_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_payment_state_read_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_payment_state_read_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_state_read'))
    )
    op.create_index('ix_payment_state_read_case_id_read_at', 'payment_state_read', ['case_id', 'read_at'], unique=False)
    op.create_index('ix_payment_state_read_merchant_id_provider_payment_id', 'payment_state_read', ['merchant_id', 'provider_payment_id'], unique=False)
    op.create_table('candidate_estimate',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('baseline_estimate_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('intervention_probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('action_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('risk_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('customer_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), server_default='REAL', nullable=False),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("availability <> 'UNAVAILABLE' OR unavailable_reason IS NOT NULL", name=op.f('ck_candidate_estimate_unavailable_requires_reason')),
    sa.CheckConstraint('"action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_candidate_estimate_action_enum')),
    sa.CheckConstraint('"availability" IN (\'AVAILABLE\', \'UNAVAILABLE\')', name=op.f('ck_candidate_estimate_availability_enum')),
    sa.CheckConstraint('"method" IN (\'DETERMINISTIC\', \'PRIOR_FALLBACK\', \'UNCALIBRATED\', \'DEFINITIONAL\')', name=op.f('ck_candidate_estimate_method_enum')),
    sa.CheckConstraint('"provenance" IN (\'REAL\', \'SYNTHETIC\')', name=op.f('ck_candidate_estimate_provenance_enum')),
    sa.CheckConstraint('action_cost >= 0', name=op.f('ck_candidate_estimate_action_cost_nonnegative')),
    sa.CheckConstraint('customer_cost >= 0', name=op.f('ck_candidate_estimate_customer_cost_nonnegative')),
    sa.CheckConstraint('intervention_probability >= 0 AND intervention_probability <= 1', name=op.f('ck_candidate_estimate_intervention_probability_in_range')),
    sa.CheckConstraint('risk_cost >= 0', name=op.f('ck_candidate_estimate_risk_cost_nonnegative')),
    sa.ForeignKeyConstraint(['baseline_estimate_id'], ['baseline_estimate.id'], name=op.f('fk_candidate_estimate_baseline_estimate_id_baseline_estimate'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_candidate_estimate_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_candidate_estimate_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], name=op.f('fk_candidate_estimate_model_version_id_model_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_estimate')),
    sa.UniqueConstraint('baseline_estimate_id', 'action', name='uq_candidate_estimate_baseline_estimate_id_action')
    )
    op.create_index('ix_candidate_estimate_case_id', 'candidate_estimate', ['case_id'], unique=False)
    op.create_table('diagnosis',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_cycle', sa.SmallInteger(), nullable=False),
    sa.Column('ai_invocation_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('substituted_to_unknown', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"cause" IN (\'INSUFFICIENT_FUNDS\', \'EXPIRED_PAYMENT_METHOD\', \'BANK_OR_NETWORK_FAILURE\', \'TECHNICAL_ISSUE\', \'ABANDONMENT\', \'CUSTOMER_ACTION_REQUIRED\', \'FRAUD_OR_RISK_SIGNAL\', \'UNKNOWN\')', name=op.f('ck_diagnosis_cause_enum')),
    sa.CheckConstraint('"method" IN (\'DETERMINISTIC\', \'AI_ASSISTED\', \'REJECTED_AI_OUTPUT\', \'FALLBACK_UNKNOWN\')', name=op.f('ck_diagnosis_method_enum')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_diagnosis_confidence_in_range')),
    sa.CheckConstraint('decision_cycle >= 0', name=op.f('ck_diagnosis_decision_cycle_nonnegative')),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocation.id'], name=op.f('fk_diagnosis_ai_invocation_id_ai_invocation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_diagnosis_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_diagnosis_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis'))
    )
    op.create_index('ix_diagnosis_case_id_decision_cycle', 'diagnosis', ['case_id', 'decision_cycle'], unique=False)
    # Guarantees: exactly one active diagnosis per decision cycle. Two would mean
    # two causes could each justify a different action, with nothing in the record
    # saying which one the recommendation was built from.
    op.create_index('one_active_diagnosis_per_cycle', 'diagnosis', ['case_id', 'decision_cycle'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('job_attempt',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('error_class', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('attempt_no >= 1', name=op.f('ck_job_attempt_attempt_no_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_attempt_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_job_attempt_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempt')),
    sa.UniqueConstraint('job_id', 'attempt_no', name='uq_job_attempt_job_id_attempt_no')
    )
    op.create_table('recommendation',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('baseline_estimate_id', sa.UUID(), nullable=False),
    sa.Column('decision_cycle', sa.SmallInteger(), nullable=False),
    sa.Column('selected_action', sa.Text(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('divergence_reason', sa.Text(), nullable=True),
    sa.Column('substituted_risk_cause', sa.Text(), nullable=True),
    sa.Column('substitution_reason', sa.Text(), nullable=True),
    sa.Column('ai_explanation_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"selected_action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_recommendation_selected_action_enum')),
    sa.CheckConstraint('"selection_reason" IN (\'HIGHEST_NET_VALUE\', \'NO_POSITIVE_VALUE\', \'HIGH_BASELINE_NO_INTERVENTION\')', name=op.f('ck_recommendation_selection_reason_enum')),
    sa.CheckConstraint('"substituted_risk_cause" IN (\'INSUFFICIENT_FUNDS\', \'EXPIRED_PAYMENT_METHOD\', \'BANK_OR_NETWORK_FAILURE\', \'TECHNICAL_ISSUE\', \'ABANDONMENT\', \'CUSTOMER_ACTION_REQUIRED\', \'FRAUD_OR_RISK_SIGNAL\', \'UNKNOWN\')', name=op.f('ck_recommendation_substituted_risk_cause_enum')),
    sa.ForeignKeyConstraint(['baseline_estimate_id'], ['baseline_estimate.id'], name=op.f('fk_recommendation_baseline_estimate_id_baseline_estimate'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_recommendation_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_recommendation_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation')),
    sa.UniqueConstraint('case_id', 'decision_cycle', name='uq_recommendation_case_id_decision_cycle')
    )
    op.create_table('recovery_outcome',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('recovered_amount', sa.BigInteger(), nullable=False),
    sa.Column('recovery_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('seconds_to_recovery', sa.Integer(), nullable=True),
    sa.Column('verified_by_read_id', sa.UUID(), nullable=False),
    sa.Column('reconciled_from_terminal_state', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"classification" IN (\'NATURAL\', \'OBSERVED\', \'ATTRIBUTED\')', name=op.f('ck_recovery_outcome_classification_enum')),
    sa.CheckConstraint('"reconciled_from_terminal_state" IN (\'NEW\', \'DETECTED\', \'DIAGNOSED\', \'DECISION_PENDING\', \'POLICY_CHECK\', \'ACTION_SCHEDULED\', \'EXECUTING\', \'WAITING_FOR_OUTCOME\', \'RECOVERED\', \'STOPPED\', \'BLOCKED\', \'EXPIRED\', \'ESCALATED\', \'FAILED\')', name=op.f('ck_recovery_outcome_reconciled_from_terminal_state_enum')),
    sa.CheckConstraint('recovered_amount >= 0', name=op.f('ck_recovery_outcome_recovered_amount_nonnegative')),
    sa.CheckConstraint('seconds_to_recovery IS NULL OR seconds_to_recovery >= 0', name=op.f('ck_recovery_outcome_seconds_to_recovery_nonnegative')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_recovery_outcome_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_recovery_outcome_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_read_id'], ['payment_state_read.id'], name=op.f('fk_recovery_outcome_verified_by_read_id_payment_state_read'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_outcome')),
    sa.UniqueConstraint('case_id', name='uq_recovery_outcome_case_id')
    )
    op.create_index('ix_recovery_outcome_merchant_id_recovery_timestamp', 'recovery_outcome', ['merchant_id', 'recovery_timestamp'], unique=False)
    op.create_table('policy_decision',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('primary_reason', sa.Text(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=True),
    sa.Column('rule_set_version', sa.Text(), nullable=False),
    sa.Column('config_version', sa.Text(), nullable=True),
    sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('earliest_permitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('selected_action', sa.Text(), nullable=False),
    sa.Column('case_state_at_evaluation', sa.Text(), nullable=False),
    sa.Column('consumed_by_intent_id', sa.UUID(), nullable=True),
    sa.Column('decision_cycle', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"case_state_at_evaluation" IN (\'NEW\', \'DETECTED\', \'DIAGNOSED\', \'DECISION_PENDING\', \'POLICY_CHECK\', \'ACTION_SCHEDULED\', \'EXECUTING\', \'WAITING_FOR_OUTCOME\', \'RECOVERED\', \'STOPPED\', \'BLOCKED\', \'EXPIRED\', \'ESCALATED\', \'FAILED\')', name=op.f('ck_policy_decision_case_state_at_evaluation_enum')),
    sa.CheckConstraint('"selected_action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_policy_decision_selected_action_enum')),
    sa.CheckConstraint('"verdict" IN (\'APPROVED\', \'BLOCKED\', \'DEFERRED\', \'ESCALATE\')', name=op.f('ck_policy_decision_verdict_enum')),
    sa.CheckConstraint('expires_at > evaluated_at', name=op.f('ck_policy_decision_validity_window_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_policy_decision_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_policy_decision_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_policy_decision_recommendation_id_recommendation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['policy_rule_set.id'], name=op.f('fk_policy_decision_rule_set_id_policy_rule_set'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decision'))
    )
    op.create_index('ix_policy_decision_case_id_evaluated_at', 'policy_decision', ['case_id', 'evaluated_at'], unique=False)
    op.create_index('ix_policy_decision_merchant_id_earliest_permitted_at', 'policy_decision', ['merchant_id', 'earliest_permitted_at'], unique=False)
    # Guarantees: one approval authorizes at most one external effect. Partial on
    # NOT NULL so the many unconsumed decisions do not collide with each other.
    op.create_index('one_intent_per_decision', 'policy_decision', ['consumed_by_intent_id'], unique=True, postgresql_where=sa.text('consumed_by_intent_id IS NOT NULL'))
    op.create_table('recommendation_candidate',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('candidate_estimate_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('incremental_probability', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('expected_incremental_revenue', sa.BigInteger(), nullable=False),
    sa.Column('action_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('risk_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('customer_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('net_recovery_value', sa.BigInteger(), nullable=False),
    sa.Column('excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_recommendation_candidate_action_enum')),
    sa.CheckConstraint('"exclusion_reason" IN (\'CAUSE_NOT_ELIGIBLE\', \'PROVIDER_CAPABILITY_UNVERIFIED\', \'NON_POSITIVE_INCREMENTAL_VALUE\', \'COST_RATIO_EXCEEDED\', \'INVALID_ESTIMATE_INPUT\', \'BELOW_NET_VALUE_THRESHOLD\', \'BELOW_INCREMENTAL_PROBABILITY\')', name=op.f('ck_recommendation_candidate_exclusion_reason_enum')),
    sa.CheckConstraint('action_cost >= 0', name=op.f('ck_recommendation_candidate_action_cost_nonnegative')),
    sa.CheckConstraint('customer_cost >= 0', name=op.f('ck_recommendation_candidate_customer_cost_nonnegative')),
    sa.CheckConstraint('excluded = (exclusion_reason IS NOT NULL)', name=op.f('ck_recommendation_candidate_exclusion_reason_iff_excluded')),
    sa.CheckConstraint('incremental_probability >= -1 AND incremental_probability <= 1', name=op.f('ck_recommendation_candidate_incremental_probability_in_range')),
    sa.CheckConstraint('risk_cost >= 0', name=op.f('ck_recommendation_candidate_risk_cost_nonnegative')),
    sa.ForeignKeyConstraint(['candidate_estimate_id'], ['candidate_estimate.id'], name=op.f('fk_recommendation_candidate_candidate_estimate_id_candidate_estimate'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_recommendation_candidate_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], name=op.f('fk_recommendation_candidate_recommendation_id_recommendation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_candidate')),
    sa.UniqueConstraint('recommendation_id', 'action', name='uq_recommendation_candidate_recommendation_action')
    )
    # INVARIANT: exactly one external effect per authorization.
    # uq_execution_intent_merchant_id_idempotency_key. The intent row is committed
    # before the provider is called, so a retry that recomputes the same key collides
    # here and reconciles instead of issuing a second call. The same key is sent to
    # the provider as reference_id, so their side rejects a duplicate too.
    op.create_table('execution_intent',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('policy_decision_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('attempt_ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempt_started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('provider_response_id', sa.Text(), nullable=True),
    sa.Column('provider_short_url', sa.Text(), nullable=True),
    sa.Column('provider_failure_code', sa.Text(), nullable=True),
    sa.Column('is_post_payment', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reconciliation_attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('counter_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(state IN ('CONFIRMED', 'FAILED')) = (resolved_at IS NOT NULL)", name=op.f('ck_execution_intent_resolved_at_iff_resolved')),
    sa.CheckConstraint('"action" IN (\'DO_NOTHING\', \'WAIT\', \'RETRY\', \'DELAYED_RETRY\', \'PAYMENT_LINK\', \'CUSTOMER_MESSAGE\', \'PAYMENT_METHOD_UPDATE\', \'PROMISE_TO_PAY_FOLLOW_UP\', \'HUMAN_ESCALATION\')', name=op.f('ck_execution_intent_action_enum')),
    sa.CheckConstraint('"state" IN (\'ATTEMPTED\', \'CONFIRMED\', \'FAILED\', \'UNCERTAIN\')', name=op.f('ck_execution_intent_state_enum')),
    sa.CheckConstraint('attempt_ordinal >= 1', name=op.f('ck_execution_intent_attempt_ordinal_positive')),
    sa.CheckConstraint('reconciliation_attempts >= 0', name=op.f('ck_execution_intent_reconciliation_attempts_nonnegative')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_case.id'], name=op.f('fk_execution_intent_case_id_recovery_case'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_execution_intent_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decision.id'], name=op.f('fk_execution_intent_policy_decision_id_policy_decision'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_intent')),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_execution_intent_merchant_id_idempotency_key')
    )
    op.create_index('ix_execution_intent_case_id_attempt_ordinal', 'execution_intent', ['case_id', 'attempt_ordinal'], unique=False)
    # Reason: the reconciliation sweeper. Partial on the two unresolved states,
    # because the resolved rows are the overwhelming majority and indexing them
    # would make this scan read what it is trying to skip.
    op.create_index('ix_execution_intent_unresolved', 'execution_intent', ['state', 'attempt_started_at'], unique=False, postgresql_where=sa.text("state IN ('ATTEMPTED', 'UNCERTAIN')"))
    op.create_table('policy_check_result',
    sa.Column('policy_decision_id', sa.UUID(), nullable=False),
    sa.Column('check_order', sa.SmallInteger(), nullable=False),
    sa.Column('check_id', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"check_id" IN (\'ALREADY_PAID\', \'ALREADY_TERMINAL\', \'DUPLICATE_ACTION\', \'FRAUD_OR_RISK\', \'CUSTOMER_OPTED_OUT\', \'CONSENT_MISSING\', \'HUMAN_OWNERSHIP\', \'WINDOW_EXPIRED\', \'MAX_ATTEMPTS_REACHED\', \'MAX_MESSAGES_REACHED\', \'COOLDOWN_ACTIVE\', \'ACTION_NOT_ELIGIBLE\')', name=op.f('ck_policy_check_result_check_id_enum')),
    sa.CheckConstraint('"outcome" IN (\'PASS\', \'FAIL\', \'UNAVAILABLE\')', name=op.f('ck_policy_check_result_outcome_enum')),
    sa.CheckConstraint('check_order >= 1 AND check_order <= 12', name=op.f('ck_policy_check_result_check_order_within_fixed_order')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_policy_check_result_merchant_id_merchant'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decision.id'], name=op.f('fk_policy_check_result_policy_decision_id_policy_decision'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_check_result')),
    sa.UniqueConstraint('policy_decision_id', 'check_order', name='uq_policy_check_result_policy_decision_id_check_order')
    )

    # The four invariant-carrying objects, commented in the database itself. A
    # comment in this file helps whoever reads the migration; a COMMENT ON helps
    # whoever is looking at the schema in psql wondering whether an index that
    # "looks redundant" can be dropped. It cannot.
    for statement in _INVARIANT_COMMENTS:
        op.execute(statement)


def downgrade() -> None:
    # Drops everything, in reverse dependency order. Present because Alembic wants a
    # reverse, not because running it against anything holding real data would be a
    # good idea — it would take the audit log with it.
    op.drop_table('policy_check_result')
    op.drop_index('ix_execution_intent_unresolved', table_name='execution_intent', postgresql_where=sa.text("state IN ('ATTEMPTED', 'UNCERTAIN')"))
    op.drop_index('ix_execution_intent_case_id_attempt_ordinal', table_name='execution_intent')
    op.drop_table('execution_intent')
    op.drop_table('recommendation_candidate')
    op.drop_index('one_intent_per_decision', table_name='policy_decision', postgresql_where=sa.text('consumed_by_intent_id IS NOT NULL'))
    op.drop_index('ix_policy_decision_merchant_id_earliest_permitted_at', table_name='policy_decision')
    op.drop_index('ix_policy_decision_case_id_evaluated_at', table_name='policy_decision')
    op.drop_table('policy_decision')
    op.drop_index('ix_recovery_outcome_merchant_id_recovery_timestamp', table_name='recovery_outcome')
    op.drop_table('recovery_outcome')
    op.drop_table('recommendation')
    op.drop_table('job_attempt')
    op.drop_index('one_active_diagnosis_per_cycle', table_name='diagnosis', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_diagnosis_case_id_decision_cycle', table_name='diagnosis')
    op.drop_table('diagnosis')
    op.drop_index('ix_candidate_estimate_case_id', table_name='candidate_estimate')
    op.drop_table('candidate_estimate')
    op.drop_index('ix_payment_state_read_merchant_id_provider_payment_id', table_name='payment_state_read')
    op.drop_index('ix_payment_state_read_case_id_read_at', table_name='payment_state_read')
    op.drop_table('payment_state_read')
    op.drop_index('ix_memory_observation_merchant_id_intervention_status', table_name='memory_observation')
    op.drop_table('memory_observation')
    op.drop_index('one_pending_job_per_dedupe_key', table_name='job', postgresql_where=sa.text("state = 'PENDING' AND dedupe_key IS NOT NULL"))
    op.drop_index('ix_job_state_run_after', table_name='job')
    op.drop_index('ix_job_merchant_id_kind', table_name='job')
    op.drop_table('job')
    op.drop_index('ix_experiment_assignment_experiment_id_group', table_name='experiment_assignment')
    op.drop_table('experiment_assignment')
    op.drop_index('ix_detection_verdict_merchant_id_decided_at', table_name='detection_verdict')
    op.drop_table('detection_verdict')
    op.drop_index('ix_baseline_estimate_merchant_id_segment_id', table_name='baseline_estimate')
    op.drop_index('ix_baseline_estimate_case_id_decision_cycle', table_name='baseline_estimate')
    op.drop_table('baseline_estimate')
    op.drop_index('ix_audit_record_merchant_id_occurred_at', table_name='audit_record')
    op.drop_index('ix_audit_record_correlation_id', table_name='audit_record')
    op.drop_table('audit_record')
    op.drop_index('ix_ai_invocation_merchant_id_created_at', table_name='ai_invocation')
    op.drop_index('ix_ai_invocation_case_id', table_name='ai_invocation')
    op.drop_table('ai_invocation')
    op.drop_index('ix_webhook_secret_merchant_id_activated_at', table_name='webhook_secret')
    op.drop_table('webhook_secret')
    op.drop_index('one_open_case_per_payment', table_name='recovery_case', postgresql_where=sa.text("state NOT IN ('BLOCKED', 'ESCALATED', 'EXPIRED', 'FAILED', 'RECOVERED', 'STOPPED')"))
    op.drop_index('ix_recovery_case_merchant_id_state_window_end_at', table_name='recovery_case')
    op.drop_index('ix_recovery_case_merchant_id_detected_at', table_name='recovery_case')
    op.drop_index('ix_recovery_case_merchant_id_customer_key', table_name='recovery_case')
    op.drop_table('recovery_case')
    op.drop_index('one_active_rule_set_per_merchant', table_name='policy_rule_set', postgresql_where=sa.text('is_active'))
    op.drop_table('policy_rule_set')
    op.drop_index('ix_model_promotion_model_version_id', table_name='model_promotion')
    op.drop_table('model_promotion')
    op.drop_table('experiment_version_freeze')
    op.drop_index('one_active_config_per_key', table_name='app_config', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_app_config_merchant_id_key', table_name='app_config')
    op.drop_table('app_config')
    op.drop_index('ix_webhook_event_merchant_id_received_at', table_name='webhook_event')
    op.drop_index('ix_webhook_event_correlation_id', table_name='webhook_event')
    op.drop_table('webhook_event')
    op.drop_table('synthetic_run')
    op.drop_index('one_active_model_version_per_component', table_name='model_version', postgresql_where=sa.text("state = 'ACTIVE'"))
    op.drop_table('model_version')
    op.drop_table('merchant_user')
    op.drop_index('ix_experiment_merchant_id_state', table_name='experiment')
    op.drop_table('experiment')
    op.drop_index('ix_event_quarantine_merchant_id_retain_until', table_name='event_quarantine')
    op.drop_table('event_quarantine')
    op.drop_index('ix_customer_consent_merchant_id_customer_key', table_name='customer_consent')
    op.drop_table('customer_consent')
    op.drop_table('merchant')
